In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
ser1 = Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['X','Y'])

In [6]:
ser1

T    0
U    1
V    2
dtype: int64

In [7]:
ser2

X    3
Y    4
dtype: int64

In [8]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [10]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [11]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])
dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])
dframe1

X         Y         Z
0  0.883017 -1.254270 -0.550362
1  0.767099 -0.859108  0.407110
2 -1.239122 -1.617079  1.043092
3 -1.650321 -0.306960  1.280393

In [12]:
dframe2

Y         Q         X
0  0.618830  0.876004 -1.025311
1  0.900084  0.917681 -0.167669
2 -1.183556 -1.041039 -0.983875

In [13]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN  0.883017 -1.254270 -0.550362
1       NaN  0.767099 -0.859108  0.407110
2       NaN -1.239122 -1.617079  1.043092
3       NaN -1.650321 -0.306960  1.280393
0  0.876004 -1.025311  0.618830       NaN
1  0.917681 -0.167669  0.900084       NaN
2 -1.041039 -0.983875 -1.183556       NaN

In [14]:
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN  0.883017 -1.254270 -0.550362
1       NaN  0.767099 -0.859108  0.407110
2       NaN -1.239122 -1.617079  1.043092
3       NaN -1.650321 -0.306960  1.280393
4  0.876004 -1.025311  0.618830       NaN
5  0.917681 -0.167669  0.900084       NaN
6 -1.041039 -0.983875 -1.183556       NaN